<a href="https://colab.research.google.com/github/derekhatherley/ds2002-fa26/blob/main/2026_09_25_%E2%80%94_Cleaning_Gauntlet_%E2%80%94_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Cleaning Gauntlet

**Lab — 2026-09-25 · Fall 2026**  

---

## Lab 05 — Cleaning Gauntlet

Three hundred rows, generated messy. This is the first dataset in the course you cannot eyeball, which means you have to work from counts and assertions rather than from looking at the table and deciding it seems fine.

Deliverables: a clean frame, a decision log, a set of assertions that pass, and one business number at the end — revenue by category — that you would be willing to defend.

Keep the log as you go. Reconstructing it afterward is much harder than writing one line per step, and the write-up at the end depends on it.

### The log

Run this first, then call `log(...)` after each cleaning step.

In [1]:
DECISIONS = []

def log(step, decision, rows_affected):
    DECISIONS.append({'step': step, 'decision': decision, 'rows': rows_affected})
    print(f'[{step}] {decision} ({rows_affected} row(s))')

In [2]:
import pandas as pd, numpy as np
from io import StringIO
rng = np.random.default_rng(5)
items = ['Cheeseburger','cheese burger','Foam Finger','foam finger','Rain Poncho','rain poncho']
cats = ['Food','food','Merch','Apparel','RainGear','rain-gear']
rows = []
for i in range(300):
    rows.append({
        'order_id': i,
        'item': rng.choice(items),
        'category': rng.choice(cats),
        'qty': rng.choice([1,2,3,-1,np.nan], p=[.5,.25,.15,.05,.05]),
        'price': rng.choice(['$7.50','7.5','$12.00','24','6.0']),
    })
df = pd.DataFrame(rows)
df = pd.concat([df, df.sample(15, random_state=1)])  # inject dupes
df.head()

   order_id           item  category  qty   price
0         0    Rain Poncho  RainGear  3.0  $12.00
1         1    foam finger   Apparel  1.0     7.5
2         2  cheese burger     Merch  1.0   $7.50
3         3   Cheeseburger      Food  NaN   $7.50
4         4  cheese burger   Apparel  1.0     7.5

### TODO 1 — drop duplicates

In [26]:
# TODO
original_rows = len(df)
cleandf = df.copy()
cleandf = cleandf.drop_duplicates().reset_index(drop = True)
new_rows = len(cleandf)
affected_rows = original_rows - new_rows
log('Drop duplicates', 'Copied original data and removed duplicate rows', affected_rows)
cleandf.head()

[Drop duplicates] Copied original data and removed duplicate rows (15 row(s))

   order_id           item  category  qty   price
0         0    Rain Poncho  RainGear  3.0  $12.00
1         1    foam finger   Apparel  1.0     7.5
2         2  cheese burger     Merch  1.0   $7.50
3         3   Cheeseburger      Food  NaN   $7.50
4         4  cheese burger   Apparel  1.0     7.5

### TODO 2 — clean `price` -> float

In [31]:
# TODO

affected_rows = cleandf['price'].astype(str).str.contains('$').sum()
cleandf['price'] = cleandf['price'].astype(str)
cleandf['price'] = cleandf['price'].replace('$', '')
cleandf['price'] = cleandf['price'].astype(float)
log('Clean price', 'Removed all dollar signs and changed data type to float', affected_rows)
cleandf.head()

ValueError: could not convert string to float: np.str_('$12.00')

### TODO 3 — `qty` -> numeric, drop rows with missing/negative qty

In [32]:
# TODO

affected_rows = cleandf['qty'].isna().sum() + (cleandf['qty'] < 0).sum()
cleandf = cleandf.dropna()
cleandf = cleandf[cleandf['qty'] > 0]
cleandf['qty'] = cleandf['qty'].astype(int)
log('Clean qty', 'Removed NaN or negative quantity values', affected_rows)
cleandf.head()

[Clean qty] Removed NaN or negative quantity values (0 row(s))

   order_id           item  category  qty   price
0         0    Rain Poncho  RainGear    3  $12.00
1         1    foam finger   Apparel    1     7.5
2         2  cheese burger     Merch    1   $7.50
4         4  cheese burger   Apparel    1     7.5
5         5    Foam Finger      food    3     6.0

### TODO 4 — canonicalize `item`

Six spellings, three real products. Start by listing what you actually have, then build the mapping from that list rather than from memory.

```python
print(df['item'].value_counts())
ITEM_MAP = {...}
```

In [ ]:
# TODO: inspect the variants, build a mapping dict, apply it, log the collapse

### TODO 5 — normalize `category`

Same approach. Note that `Apparel` and `Merch` are a business decision, not a string problem — decide and log it.

In [ ]:
# TODO

### TODO 6 — prove it's clean

**TODO:** uncomment these and add two more assertions of your own — one about the item names and one about the categories.

In [ ]:
# assert df.duplicated().sum() == 0
# assert df['qty'].min() >= 1
# assert df['price'].dtype == float
# TODO: assert something about item
# TODO: assert something about category
print('clean:', df.shape)

### TODO 7 — the number you would report

**TODO:** add a `revenue` column, then print revenue by category, highest first, plus the overall total. Round money to two decimals.

Then, in one sentence, state what you would tell a vendor to stock more of.

In [ ]:
# TODO

**What I would tell the vendor:** _..._

### TODO 8 — read back your log

In [ ]:
import pandas as pd
pd.DataFrame(DECISIONS)

### Write-up

Two parts.

**a)** Which cleaning step changed your revenue total the most? Give the number before and after that step, not a description.

**b)** Pick one decision you made where a reasonable person could have chosen differently. State the other choice, what it would have done to your reported revenue, and why you went the way you did.

_your answer here_